version: '3'
services:
  frontend:
    build: .
    ports:
      - "5173:5173"
    depends_on:
      - backend
    command: serve -s dist -l 5173

  backend:
    image: node:18-alpine
    working_dir: /app
    volumes:
      - ./db.json:/app/db.json
    command: npx json-server --watch db.json --port 3000
    ports:
      - "3000:3000"
